###################################################
### RefineTemplateManager configuration example ###
###################################################
# An example YAML configuration to modify.
# Call `RefineTemplateManager.from_yaml(path)` to load this configuration.
template_volume_path: /some/path/to/template.mrc
particle_stack:
  df_path: /some/path/to/particles.csv  # Needs to be readable by pandas
  extracted_box_size: [528, 528]
  original_template_size: [512, 512]
defocus_refinement_config:
  defocus_max:  100.0  # in Angstroms, relative to "best" defocus value in particle stack dataframe
  defocus_min: -100.0  # in Angstroms, relative to "best" defocus value in particle stack dataframe
  defocus_step: 20.0   # in Angstroms
  enabled: true
orientation_refinement_config:
  in_plane_angular_step_coarse:     1.5   # in degrees
  in_plane_angular_step_fine:       0.15  # in degrees
  out_of_plane_angular_step_coarse: 2.5   # in degrees
  out_of_plane_angular_step_fine:   0.25  # in degrees
preprocessing_filters:
  whitening_filter:
    do_power_spectrum: true
    enabled: true
    max_freq: 0.5  # In terms of Nyquist frequency
    num_freq_bins: null
  bandpass_filter:
    enabled: false
    falloff: null
    high_freq_cutoff: null
    low_freq_cutoff: null
computational_config:
  gpu_ids: 0
  num_cpus: 1